apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "enrollment.name" . }}-config
  labels:
    {{- include "enrollment.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
